Resources:
  EventBridgeToSnsPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sns:Publish
            Resource: !Ref SnsFormSubmittedTopic
      Topics:
        - !Ref SnsFormSubmittedTopic
# Allows for Eventbridge events to be forwarded to the SNS Topic
