Resources:
  SnsSubToIngressQeue:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: ${self:custom.INGRESS_SQS_ARN}
      Protocol: sqs
      RawMessageDelivery: true
      TopicArn: !Ref SnsFormSubmittedTopic
